Repository AY2324S2-CS2103T-F14-3/tp, pull requests merged in 2024-03, with the labels that each got.

#18 Add Kailash's AboutUs information
  docs/AboutUs.md
  docs/images/kailashgautham.png
  docs/team/kailashgautham.md
Labels: type.Documentation

#15 Add Tejas's AboutUs information
  docs/AboutUs.md
  docs/images/tejas.png
  docs/team/tejasgarrepally.md
Labels: type.Documentation

#25 Add Axel's AboutUs information
  docs/AboutUs.md
  docs/images/teojunda.png
  docs/team/teojunda.md
Labels: type.Documentation

#27 Adapted readme for current project
  README.md
  docs/images/Ui.png
Labels: type.Documentation

#30 Update Developer Guide
  docs/DeveloperGuide.md
Labels: type.Documentation

#35 Remove ab3 traces
  docs/UserGuide.md
Labels: type.Documentation

#37 Add use cases in developer guide
  docs/DeveloperGuide.md
Labels: type.Documentation

#38 Implement Add Command
  README.md
  docs/index.md
  src/main/java/seedu/address/commons/util/ToStringBuilder.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/ClassGroup.java
  src/main/java/seedu/address/model/person/Github.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Telegram.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High, type.Story

#39 Modify user guide for add command
  docs/UserGuide.md
Labels: type.Documentation

#42 Fix isSamePerson check
  src/main/java/seedu/address/model/person/Github.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Telegram.java
Labels: bug

#43 Axel/edit command
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: priority.High

#46 Modify delete command word to follow other command
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
Labels: priority.Low

#51 Extend `ListCommand` functionality
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ListCommandParser.java
  src/main/java/seedu/address/model/person/ClassGroup.java
  src/main/java/seedu/address/model/person/ListCommandPredicate.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/model/person/ClassGroupTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High, type.Story

#52 Make changes to PUML Diagrams ...
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
Labels: type.Documentation

#53 Make changes to PUML diagram
  docs/diagrams/ModelClassDiagram.puml
Labels: type.Documentation, priority.Low

#55 Add View Command
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ViewCommandParser.java
  src/test/java/seedu/address/logic/commands/ViewCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ViewCommandParserTest.java
Labels: priority.High

#57 Include implementation details of Edit Command in Developer Guide
  docs/DeveloperGuide.md
  docs/diagrams/EditCommandActivityDiagram.puml
  docs/diagrams/EditCommandSequenceDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
Labels: type.Documentation

#59 Make changes to PUML Diagrams
  docs/DeveloperGuide.md
  docs/diagrams/DeleteSequenceDiagram.puml
Labels: type.Documentation

#62 Remove extra if block
  docs/diagrams/ViewCommandActivityDiagram.puml
Labels: type.Documentation

#66 Add logging to add command code
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
Labels: enhancement

#70 Add logging to view command code
  src/main/java/seedu/address/logic/commands/ViewCommand.java
Labels: enhancement, priority.Low

#68 Add logging for `ListCommand.java`
  src/main/java/seedu/address/logic/commands/ListCommand.java
Labels: priority.Low

#73 Add assertions to `DeleteCommand.java`
  build.gradle
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
Labels: priority.Low

#76 Add logging for EditCommand
  src/main/java/seedu/address/logic/commands/EditCommand.java
Labels: enhancement, priority.Low

#78 Change `Phone` to be an optional field for `Person`
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Github.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/SidePanel.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: enhancement

#72 Add changes to developer guide
  docs/DeveloperGuide.md
Labels: type.Documentation

#86 Update dependencies relating to Mark Command
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: enhancement

#89 Update documentation to include Attendance and Notes
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
Labels: type.Documentation

#94 Fix bug
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/person/Person.java
Labels: bug

#96 Update add note command to follow edit command format
  src/main/java/seedu/address/logic/commands/AddNoteCommand.java
  src/main/java/seedu/address/logic/parser/AddNoteCommandParser.java
  src/test/java/seedu/address/logic/parser/AddNoteCommandParserTest.java
Labels: priority.Low

#97 Update UIClass Diagram & View Command DG
  docs/DeveloperGuide.md
  docs/diagrams/UiClassDiagram.puml
  docs/diagrams/ViewCommandActivityDiagram.puml
Labels: type.Documentation

#99 Add noteview in sidepanel
  src/main/java/seedu/address/model/person/Notes.java
  src/main/java/seedu/address/ui/SidePanel.java
  src/main/resources/view/SidePanel.fxml
  src/test/java/seedu/address/model/person/NotesTest.java
Labels: enhancement, priority.Low

#103 Ivan's UG + Assertions
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/ViewCommand.java
Labels: type.Documentation

#104 Implement deleteNote command
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteNoteCommand.java
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/parser/AddNoteCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteNoteCommandParser.java
  src/main/java/seedu/address/logic/parser/MarkCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Notes.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/DeleteNoteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteNoteCommandParserTest.java
  src/test/java/seedu/address/model/person/NotesTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: enhancement
