Repository AY2324S2-CS2103T-F14-3/tp, pull requests merged in 2024-04, with the labels that each got.

#108 Add Nord Light theme
  src/main/java/seedu/tatoolkit/ui/UiManager.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/NordTheme.css
  src/main/resources/view/SidePanel.fxml
Labels: priority.Low

#109 Update Developer Guide
  docs/DeveloperGuide.md
Labels: type.Documentation

#111 Include addnote and deletenote in userguide
  docs/UserGuide.md
Labels: type.Documentation

#115 Update user guide according to CA3 guidelines
  docs/UserGuide.md
  docs/images/ActualUi.png
  docs/images/ErrorMessage_example.png
  docs/images/InterfaceWalkthrough.png
  docs/images/ac_example.png
  docs/images/an_example.png
  docs/images/findAlexDavidResult.png
  docs/images/find_example.png
  docs/images/helpMessage.png
  docs/images/uc_example.png
  docs/images/view_example.png
Labels: type.Documentation

#112 Add attendance view on side panel
  .gitignore
  src/main/java/seedu/tatoolkit/logic/Logic.java
  src/main/java/seedu/tatoolkit/logic/LogicManager.java
  src/main/java/seedu/tatoolkit/logic/commands/MarkCommand.java
  src/main/java/seedu/tatoolkit/model/Model.java
  src/main/java/seedu/tatoolkit/model/ModelManager.java
  src/main/java/seedu/tatoolkit/model/attendance/Attendance.java
  src/main/java/seedu/tatoolkit/ui/MainWindow.java
  src/main/java/seedu/tatoolkit/ui/SidePanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/NordTheme.css
  src/main/resources/view/SidePanel.fxml
  src/test/data/JsonSerializableTaToolkitTest/typicalPersonsTaToolkit.json
  src/test/java/seedu/tatoolkit/logic/commands/AddCommandTest.java
Labels: priority.High

#119 Add key word and parameter section to user guide
  README.md
  docs/UserGuide.md
  src/main/java/seedu/tatoolkit/model/ModelManager.java
  src/main/java/seedu/tatoolkit/model/person/ClassGroup.java
Labels: type.Documentation

#163 Update developer guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/kailashgautham.md
  docs/team/teojunda.md
  src/main/java/seedu/tatoolkit/logic/commands/ClearCommand.java
Labels: bug, type.Documentation

#171 Make changes to ug
  docs/UserGuide.md
Labels: bug

#173 Fix scrollbar issue for ls command
  src/main/resources/view/SidePanel.fxml
Labels: bug

#179 Add planned enhancement to dg
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/team/g-tejas.md
  docs/team/kailashgautham.md
Labels: type.Documentation

#184 Update images in UG
  docs/UserGuide.md
  docs/images/ActualUi.png
  docs/images/InterfaceWalkthrough.png
  docs/images/ac_example.png
  docs/images/an_example.png
  docs/images/find_example.png
  docs/images/uc_example.png
  docs/images/view_example.png
  docs/team/teojunda.md
Labels: type.Documentation

#187 Add acknowledgement for Copilot
  docs/DeveloperGuide.md
Labels: type.Documentation

#188 Add new planned enhancement
  docs/DeveloperGuide.md
Labels: type.Documentation

#193 Update planned enhancements
  docs/DeveloperGuide.md
Labels: type.Documentation
